name: Build & Deploy MkDocs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]          # build preview for PRs

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # let the action push to gh-pages
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material

      - name: Build
        run: mkdocs build -d site

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
